name: 'Test Reporter'

on: 
  workflow_call:
    inputs:
      artifact:
        required: true
        type: string

jobs:
  Report:
    runs-on: ubuntu-latest
    steps:
    - uses: dorny/test-reporter@v1
      with:
        artifact: '${{ github.event.inputs.artifact }}'
        name: Reporter
        path: '*.xml'
        reporter: java-junit
        fail-on-error: false
