name: 'Test Reporter'

on: 
  workflow_call:
    inputs:
      a:
        required: true
        type: string

jobs:
  Report:
    runs-on: ubuntu-latest
    steps:
    - uses: dorny/test-reporter@v1
      with:
        artifact: ${{ inputs.a }}
        name: Reporter
        path: '*.xml'
        reporter: java-junit
        fail-on-error: false
