name: 'Clean'

on:
  workflow_run:
    workflows: ['Unit Test Reporter']
    types:
      - completed
jobs:
  Delete:
    runs-on: ubuntu-latest
    steps:
      - run: echo '${{ toJson(github) }}'
      # - name: Demo
      #   uses: actions/github-script@v6
      #   with:
      #     script: |
      #       await github.rest.actions.deleteWorkflowRun({
      #         run_id: ${{ github.event.workflow_run.id }},
      #         owner: context.repo.owner,
      #         repo: context.repo.repo
      #       })
