name: 'Clean'

on:
  workflow_run:
    workflows: ['Test CI', Push Reporter]
    types:
      - completed
jobs:
  Create_Report:
    runs-on: ubuntu-latest
    steps:
      - run: echo "${{ toJSON(github.event) }}"
      - name: Demo
        uses: actions/github-script@v6
        with:
          script: |
            await github.rest.actions.deleteWorkflowRunLogs({
              run_id: github.event.workflow_run.id,
              owner: context.repo.owner,
              repo: context.repo.repo
            })