name: Notifier

on:
  workflow_call:
    inputs:
      body:
        required: true
        type: string

 
jobs:
  Sender:
    runs-on: ubuntu-latest
    steps:
      - name: Send
        if: github.event_name == 'push'
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: ${{ secrets.SMTP_HOST }}
          server_port: ${{ secrets.SMTP_PORT }}
          username: ${{ secrets.SMTP_USERNAME }}
          password: ${{ secrets.SMTP_PASSWORD }}
          subject: '🔥 [GITHUB BOT][FAILED] Push report (Unit test failed)'
          from: Github Action Bot
          to: ${{ secrets.SMTP_RECEIVER }}
          body: |
            Push created by has been failed.