name: Release Helper

on:
  push:
    tags:
      - 'v*.*.*'
 
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: '8'
        cache: 'maven'
    - name: Parse Tag
      uses: actions/github-script@v6
      with:
          script: |
            const tag = context.ref.replace('refs\/tags\/', '')
            core.exportVariable('tag', tag)
    - name: Publish
      run: mvn deploy \
            --settings .settings.xml \
            -Denv.NEXUS_USERNAME=admin \
            -Denv.NEXUS_PASS=123123 \
            -Denv.NEXUS_REPO_RELEASE=https://8081-gitpodio-springpetclinic-u2h6vnmoh9s.ws-us38.gitpod.io/repository/maven-releases/ \
            -Dmaven.test.skip=true
    - name: Release notes generator
      uses: Decathlon/release-notes-generator-action@v3.1.5
