name: Release Helper

on:
  push:
    tags:
      - 'v*.*.*'
 
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@master
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: '8'
        cache: 'maven'
    - name: Parse Tag
      uses: actions/github-script@v6
      with:
          script: |
            const tag = context.ref.replace('/refs/tags/', '')
            console.log(tag)
            await github.core.exportVariable('tag', tag)
    - name: Get result
      run: echo $tag
