name: 'Unit Test Reporter'

on: workflow_dispatch
  # workflow_run:
  #   workflows: ['Unit Test & Coverage']
  #   types:
  #     - completed
jobs:
  Check:
    runs-on: ubuntu-latest
    outputs:
      isPR: ${{ steps.main.outputs.valid }}
    env:
      isPR: ${{ github.event.workflow_run.conclusion == 'failure' || github.event.workflow_run.event == 'pull_request' }}
    steps:
      - name: Check
        id: main
        run: echo '::set-output name=valid::${{ env.PR }}'
  Create_Report:
    runs-on: ubuntu-latest
    needs: [Check]
    if: needs.Check.outputs.isPR == 'true'
    steps:
    - uses: dorny/test-reporter@v1
      with:
        artifact: test-results
        name: Reporter
        path: '*.xml'
        reporter: java-junit
        fail-on-error: false
        