name: Test CI

on:
  pull_request:
    branches: 
      - master
  push:
    branches:
      - master
 
jobs:
  Handle:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: '8'
        cache: 'maven'
    - name: Run test
      id: unitTest
      run: mvn test
    - name: Upload test report
      if: failure()
      uses: actions/upload-artifact@v2
      with:
        name: test-results
        path: target/surefire-reports/*.xml
    - name: Code Coverage
      uses: codecov/codecov-action@v2
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        files: jacoco.xml
        directory: ./target/site/jacoco/
    - name: Notify pusher (Success)
      if: github.event_name == 'push'
      uses: dawidd6/action-send-mail@v3
      with:
        server_address: ${{ secrets.SMTP_HOST }}
        server_port: ${{ secrets.SMTP_PORT }}
        username: ${{ secrets.SMTP_USERNAME }}
        password: ${{ secrets.SMTP_PASSWORD }}
        subject: '⭐ [GITHUB BOT][SUCCESS] Push report'
        from: Github Action Bot
        to: ${{ secrets.SMTP_RECEIVER }}
        body: |
          Push created by ${{ github.event.pusher.name }} has been succeeded.
          Detail: https://github.com/${{github.repository}}/actions/runs/${{github.run_id}}
    - name: Dump
      if: always()
      run: echo '${{ toJson(steps) }}'
    - name: Notify pusher (Failed, Other cases)
      if: failure() && github.event_name == 'push' && steps.unitTest.outputs.status != 'failure'
      uses: dawidd6/action-send-mail@v3
      with:
        server_address: ${{ secrets.SMTP_HOST }}
        server_port: ${{ secrets.SMTP_PORT }}
        username: ${{ secrets.SMTP_USERNAME }}
        password: ${{ secrets.SMTP_PASSWORD }}
        subject: '🔥 [GITHUB BOT][FAILED] Push report'
        from: Github Action Bot
        to: ${{ secrets.SMTP_RECEIVER }}
        body: |
          Push created by ${{ github.event.pusher.name }} has been failed.
          Reason: Something went wrong.
          Detail: https://github.com/${{github.repository}}/actions/runs/${{github.run_id}}
  Reporter:
    needs: [Handle]
    if: needs.Handle.result == 'failure'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        run: echo ${{ toJSON(needs) }}
    # uses: ./.github/workflows/test-reporter.yml
    # with:
    #   artifact: test-results