name: 'Test Report'
on:
  workflow_run:
    workflows: ['Unit Test & Code Coverage']
    types:
      - completed
jobs:
  report:
    runs-on: ubuntu-latest
    steps:
    - uses: dorny/test-reporter@v1
      with:
        artifact: test-results
        name: JUnit
        path: '*.xml'
        reporter: java-junit
