name: Test CI

on:
  pull_request:
    branches: 
      - master
  push:
    branches:
      - master
 
jobs:
  handle:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: '8'
        cache: 'maven'
    - name: Run test
      id: unitTest
      run: mvn test
    - name: Upload test report
      if: failure()
      uses: actions/upload-artifact@v2
      with:
        name: test-results
        path: target/surefire-reports/*.xml
    - name: Code Coverage
      uses: codecov/codecov-action@v2
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        files: jacoco.xml
        directory: ./target/site/jacoco/
  reporter:
    needs: [handle]
    runs-on: ubuntu-latest
    if: always() && (needs.handle.result == 'failure')
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Download test report
        uses: actions/download-artifact@v2
        with:
          name: test-results
          path: artifact
      - name: Report
        id: reportAction
        uses: dorny/test-reporter@v1
        with:
          name: result
          path: 'artifact/*.xml'
          reporter: java-junit
          fail-on-error: false
      - name: View context attributes
        uses: actions/github-script@v6
        with:
          script: |
            console.log(context)
      - name: View context attributes
        uses: actions/github-script@v6
        with:
          script: |
            const result = await github.rest.checks.getSuite({
              check_suite_id: context.runId,
              owner: context.repo.owner,
              repo: context.repo.repo
            })
            console.log(result)

