name: 'Unit Test Reporter'

on:
  workflow_run:
    workflows: ['Unit Test & Coverage']
    types:
      - completed
jobs:
  Check:
    runs-on: ubuntu-latest
    outputs:
      isPR: ${{ steps.main.outputs.valid }}
    steps:
      - id: main
        run: echo '::set-output name=valid::${{ github.event.workflow_run.conclusion == 'failure' && secrets.MAIN_BRANCH == github.base_ref }}'
  Create_Report:
    runs-on: ubuntu-latest
    needs: [Check]
    if: needs.Check.outputs.isPR == 'true'
    steps:
    - run: echo '${{ toJson(github) }}'
    - uses: dorny/test-reporter@v1
      with:
        artifact: test-results
        name: Reporter
        path: '*.xml'
        reporter: java-junit
        fail-on-error: false
        