name: 'Test Reporter'

on: 
  workflow_call:
    inputs:
      path:
        required: true
        type: string

jobs:
  Report:
    runs-on: ubuntu-latest
    steps:
    - uses: dorny/test-reporter@v1
      with:
        path: ${{ inputs.path }}
        name: Reporter
        reporter: java-junit
        fail-on-error: false
