name: 'Unit Test Reporter'

on:
  workflow_run:
    workflows: ['Unit Test & Coverage']
    types:
      - completed
jobs:
  Check:
    runs-on: ubuntu-latest
    outputs:
      isPR: ${{ steps.main_pr.outputs.valid }}
      isPR: ${{ steps.main_push.outputs.valid }}
    env:
      isPR: ${{ github.event.workflow_run.conclusion == 'failure' || github.event.workflow_run.event == 'pull_request' }}
      isPush: ${{ github.event.workflow_run.event == 'push' }}
    steps:
      - name: Check PR
        id: main_pr
        run: echo '::set-output name=valid::${{ env.isPR }}'
      - name: Check Push
        id: main_push
        run: echo '::set-output name=valid::${{ env.isPush }}'
  Create_Report:
    runs-on: ubuntu-latest
    needs: [Check]
    if: needs.Check.outputs.isPR == 'true'
    steps:
    - uses: dorny/test-reporter@v1
      with:
        artifact: test-results
        name: Reporter
        path: '*.xml'
        reporter: java-junit
        fail-on-error: false
  Cleanup:
    runs-on: ubuntu-latest
    needs: [Check]
    steps:
    - uses: actions/github-script@v6
      if: needs.Check.outputs.isPush == 'true'
      with:
        script: |
          const result = await github.rest.actions.createWorkflowDispatch({
            ref: context.ref,
            owner: context.repo.owner,
            repo: context.repo.repo,
            workflow_id: 'clean.yml',
            inputs: {
              something: false
            }
          })
          console.log(result)