name: Unit Test

on:
  pull_request:
    branches: 
      - master
  push:
    branches:
      - master
 
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: '8'
        cache: 'maven'
    - name: Run test
      run: mvn test
    - uses: actions/upload-artifact@v2
      if: always()
      with:
        name: test-results
        path: target/surefire-reports/*.xml
    - uses: actions/upload-artifact@v2
      with:
        name: test-results
        path: target/site/jacoco/jacoco.xml