name: Unit Test & Coverage

on: [pull_request, push]
 
jobs:
  Check:
    runs-on: ubuntu-latest
    outputs:
      isMain: ${{ steps.main.outputs.valid }}
    env:
      # isMain: ${{ (secrets.MAIN_BRANCH == github.ref_name) || (secrets.MAIN_BRANCH == github.base_ref) }}
      isMain: ${{ github.base_ref == secrets.MAIN_BRANCH }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - run: echo '${{ toJson(github) }}'
      - run: echo '${{ github.base_ref }}'
      - run: echo '${{ github.ref_name }}'
      - run: echo '${{ github.base_ref == secrets.MAIN_BRANCH }}'
      # - run: echo '${{ github.ref_name == secrets.MAIN_BRANCH }}'
      - id: main
        run: echo '::set-output name=valid::${{ env.isMain }}'
  Handle:
    needs: [Check]
    # if: needs.Check.outputs.isMain == 'true'
    runs-on: ubuntu-latest
    steps:
    - run: echo '${{ toJson(github) }}'
    - name: Checkout
      uses: actions/checkout@v2
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: '8'
        cache: 'maven'
    - name: Run test
      id: unitTest
      run: mvn test
    - name: Upload test report
      if: failure()
      uses: actions/upload-artifact@v2
      with:
        name: test-results
        path: target/surefire-reports/*.xml
    - name: Code Coverage
      uses: codecov/codecov-action@v2
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        files: jacoco.xml
        directory: ./target/site/jacoco/
