name: 'Test Reporter'

on:
  workflow_run:
    workflows: ['Unit Test']
    types:
      - completed
jobs:
  Report:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'failure' }}
    steps:
    - uses: actions/checkout@v2
    - uses: dorny/test-reporter@v2
      with:
        artifact: test-results
        name: JUnit
        path: '*.xml'
        reporter: java-junit
        fail-on-error: false
